// Localized copy is data consumed by the Analysis management view and controller.
export const analysisManagementText = {
  en: {
    tabs: { library: "Library", inbox: "Signal inbox", runners: "Desktop runners", recovery: "Legacy recovery" },
    refresh: "Refresh",
    loading: "Loading Analysis Articles…",
    loadError: "Could not load the shared Analysis library.",
    detailError: "Could not load this Article's operational history.",
    mutationError: "Could not update the notification inbox.",
    empty: "No Analysis Articles are visible with your current database grants.",
    select: "Select an Analysis Article",
    articleMeta: "Article state",
    sourceScope: "Exact source scope",
    freshness: "Freshness",
    latestRuns: "Recent runs",
    signals: "Signals",
    publications: "Fixed public publications",
    noRuns: "No runs have been recorded.",
    articleResult: "Current workspace result",
    resultAsOf: "Reviewed result",
    noCompatibleResult: "Run this exact revision successfully in DopeDB Desktop to make its reviewed result available to the team.",
    resultUnavailable: "This reviewed result is temporarily unavailable.",
    resultRevision: "Result revision",
    noSignals: "No metric signals are attached.",
    noPublications: "No fixed snapshot has been published.",
    openPublication: "Open public snapshot",
    revoked: "Revoked",
    live: "Live",
    working: "Working revision",
    manual: "Manual refresh",
    scheduled: "Scheduled refresh",
    never: "Never",
    next: "Next",
    lastSuccess: "Last success",
    openDesktop: "Editing, execution, review, recovery, and publication approval remain in DopeDB Desktop.",
    inboxEmpty: "No Analysis signal transition needs your attention.",
    markRead: "Mark selected read",
    unread: "Unread",
    read: "Read",
    block: "Block",
    runnersEmpty: "No member-owned Desktop runner is registered. Open DopeDB Desktop while signed into this workspace.",
    online: "Online",
    offline: "Offline",
    background: "Background enabled",
    foreground: "Foreground only",
    schedules: "scheduled Articles",
    lastSeen: "Last seen",
    healthy: "Ready for scheduled work",
    unavailable: "Scheduled work is unavailable",
    recoveryEmpty: "No unresolved legacy BI record remains.",
    recoveryDescription: "These definitions were preserved instead of being made executable with invented schema or sensitivity. Rebuild and review a replacement Article in Desktop, then bind it here.",
    original: "Original definition",
    replacement: "Reviewed replacement Article",
    chooseReplacement: "Choose an Article",
    resolve: "Mark recovered",
    resolving: "Saving…",
    resolved: "Recovered",
  },
  ko: {
    tabs: { library: "분석 보관함", inbox: "Signal 알림함", runners: "Desktop 실행기", recovery: "레거시 복구" },
    refresh: "새로고침",
    loading: "Analysis Article을 불러오는 중…",
    loadError: "공유 분석 보관함을 불러오지 못했습니다.",
    detailError: "이 Article의 실행 내역을 불러오지 못했습니다.",
    mutationError: "알림함 상태를 변경하지 못했습니다.",
    empty: "현재 DB 권한으로 볼 수 있는 Analysis Article이 없습니다.",
    select: "Analysis Article을 선택하세요",
    articleMeta: "Article 상태",
    sourceScope: "정확한 원본 범위",
    freshness: "최신 상태",
    latestRuns: "최근 실행",
    signals: "Signal",
    publications: "고정 공개본",
    noRuns: "기록된 실행이 없습니다.",
    articleResult: "현재 워크스페이스 결과",
    resultAsOf: "검토된 결과",
    noCompatibleResult: "이 정확한 revision을 DopeDB Desktop에서 성공적으로 실행하면 팀이 검토된 결과를 볼 수 있습니다.",
    resultUnavailable: "검토된 결과를 현재 불러올 수 없습니다.",
    resultRevision: "결과 revision",
    noSignals: "연결된 지표 Signal이 없습니다.",
    noPublications: "공개한 고정 snapshot이 없습니다.",
    openPublication: "공개 snapshot 열기",
    revoked: "회수됨",
    live: "Live",
    working: "작업 revision",
    manual: "수동 새로고침",
    scheduled: "예약 새로고침",
    never: "없음",
    next: "다음 실행",
    lastSuccess: "최근 성공",
    openDesktop: "편집·실행·검토·복구·공개 승인은 DopeDB Desktop에서 수행합니다.",
    inboxEmpty: "확인할 Analysis Signal 상태 변화가 없습니다.",
    markRead: "선택 항목 읽음",
    unread: "읽지 않음",
    read: "읽음",
    block: "블록",
    runnersEmpty: "등록된 개인 Desktop 실행기가 없습니다. 이 워크스페이스로 로그인한 DopeDB Desktop을 여세요.",
    online: "온라인",
    offline: "오프라인",
    background: "백그라운드 허용",
    foreground: "포그라운드 전용",
    schedules: "개 예약 Article",
    lastSeen: "마지막 확인",
    healthy: "예약 실행 가능",
    unavailable: "예약 실행 불가",
    recoveryEmpty: "복구되지 않은 레거시 BI 기록이 없습니다.",
    recoveryDescription: "스키마나 민감도를 추측해 실행 가능 상태로 만들지 않고 원본을 보존했습니다. Desktop에서 대체 Article을 재작성·검토한 뒤 여기에서 연결하세요.",
    original: "원본 정의",
    replacement: "검토된 대체 Article",
    chooseReplacement: "Article 선택",
    resolve: "복구 완료로 표시",
    resolving: "저장 중…",
    resolved: "복구됨",
  },
} as const;

export type AnalysisManagementText = (typeof analysisManagementText)[keyof typeof analysisManagementText];
