export const analysisManagementText = {
  en: {
    tabs: { library: "Library", recovery: "Legacy recovery" },
    refresh: "Refresh",
    loading: "Loading Analysis Articles…",
    loadError: "Could not load the shared Analysis library.",
    detailError: "Could not load this Article's run and publication history.",
    mutationError: "Could not update the legacy recovery record.",
    empty: "No Analysis Articles are visible with your current database grants.",
    select: "Select an Analysis Article",
    latestRuns: "Manual run history",
    publications: "Published HTML",
    noRuns: "This saved query has not been run yet.",
    noPublications: "No HTML page has been published.",
    openPublication: "Open published HTML",
    revoked: "Revoked",
    manual: "manual rerun",
    never: "Never",
    openDesktop: "Edit the HTML and run its saved query in DopeDB Desktop.",
    articleHtml: "Article HTML",
    savedDocument: "Saved document",
    savedQuery: "Saved query",
    recoveryEmpty: "No unresolved legacy BI record remains.",
    recoveryDescription: "Legacy BI definitions that could not become a simple HTML Article were preserved here. Rebuild one in Desktop, then bind the replacement.",
    original: "Original definition",
    replacement: "Replacement Article",
    chooseReplacement: "Choose an Article",
    resolve: "Mark recovered",
    resolving: "Saving…",
  },
  ko: {
    tabs: { library: "분석 보관함", recovery: "레거시 복구" },
    refresh: "새로고침",
    loading: "분석 아티클을 불러오는 중…",
    loadError: "공유 분석 보관함을 불러오지 못했습니다.",
    detailError: "이 아티클의 실행 및 발행 내역을 불러오지 못했습니다.",
    mutationError: "레거시 복구 기록을 변경하지 못했습니다.",
    empty: "현재 DB 권한으로 볼 수 있는 분석 아티클이 없습니다.",
    select: "분석 아티클을 선택하세요",
    latestRuns: "수동 재조회 기록",
    publications: "발행된 HTML",
    noRuns: "아직 이 저장 쿼리를 실행하지 않았습니다.",
    noPublications: "아직 발행된 HTML 페이지가 없습니다.",
    openPublication: "발행된 HTML 열기",
    revoked: "취소됨",
    manual: "수동 재조회",
    never: "없음",
    openDesktop: "HTML 편집과 저장 쿼리 재조회는 DopeDB Desktop에서 수행합니다.",
    articleHtml: "아티클 HTML",
    savedDocument: "저장 문서",
    savedQuery: "저장 쿼리",
    recoveryEmpty: "복구되지 않은 레거시 BI 기록이 없습니다.",
    recoveryDescription: "단순 HTML 아티클로 자동 변환할 수 없던 레거시 BI 정의만 보존했습니다. Desktop에서 대체 아티클을 만든 뒤 연결하세요.",
    original: "원본 정의",
    replacement: "대체 아티클",
    chooseReplacement: "아티클 선택",
    resolve: "복구 완료로 표시",
    resolving: "저장 중…",
  },
} as const;

export type AnalysisManagementText = (typeof analysisManagementText)[keyof typeof analysisManagementText];
