//! Shared SQL rendering helpers. Engine modules own capability decisions.

use std::fmt::Write as _;

use dopedb_protocol::{
    Column, ColumnDefinition, Constraint, ConstraintKind, DatabaseEngine, Index, IndexKey,
    ObjectRef, SortDirection, TableDefinition,
};

use crate::error::{AppError, AppResult};

pub(super) fn quoted_ref(engine: DatabaseEngine, reference: &ObjectRef) -> String {
    let quote = |value: &str| quote_identifier(engine, value);
    let mut parts = Vec::new();
    if let Some(catalog) = &reference.catalog {
        parts.push(quote(catalog));
    }
    if let Some(namespace) = &reference.namespace {
        parts.push(quote(namespace));
    }
    parts.push(quote(&reference.name));
    parts.join(".")
}

pub(super) fn quote_identifier(engine: DatabaseEngine, value: &str) -> String {
    match engine {
        DatabaseEngine::Mysql => format!("`{}`", value.replace('`', "``")),
        _ => format!("\"{}\"", value.replace('"', "\"\"")),
    }
}

pub(super) fn quote_literal(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

pub(super) fn column_definition(column: &Column) -> ColumnDefinition {
    ColumnDefinition {
        name: column.name.clone(),
        native_type: column.native_type.clone(),
        nullable: column.nullable,
        default_expression: column.default_expression.clone(),
        generated_expression: column.generated_expression.clone(),
        identity: column.identity,
        auto_increment: column.auto_increment,
        collation: column.collation.clone(),
        comment: column.comment.clone(),
    }
}

pub(super) fn render_column(
    engine: DatabaseEngine,
    column: &ColumnDefinition,
) -> AppResult<String> {
    let mut sql = format!(
        "{} {}",
        quote_identifier(engine, &column.name),
        column.native_type.trim()
    );
    if column.identity {
        match engine {
            DatabaseEngine::Postgres => sql.push_str(" GENERATED BY DEFAULT AS IDENTITY"),
            DatabaseEngine::Mysql => sql.push_str(" AUTO_INCREMENT"),
            DatabaseEngine::Sqlite => {
                return blocked("SQLite identity columns require an explicit INTEGER PRIMARY KEY");
            }
            DatabaseEngine::Mongodb => return blocked("MongoDB has no relational columns"),
        }
    } else if column.auto_increment {
        match engine {
            DatabaseEngine::Mysql => sql.push_str(" AUTO_INCREMENT"),
            DatabaseEngine::Postgres => {
                return blocked("PostgreSQL uses identity columns instead of auto-increment");
            }
            DatabaseEngine::Sqlite => {
                return blocked("SQLite AUTOINCREMENT is valid only on INTEGER PRIMARY KEY");
            }
            DatabaseEngine::Mongodb => return blocked("MongoDB has no relational columns"),
        }
    }
    if let Some(expression) = &column.generated_expression {
        sql.push_str(" GENERATED ALWAYS AS (");
        sql.push_str(expression.trim());
        sql.push_str(") STORED");
    } else if let Some(default) = &column.default_expression {
        sql.push_str(" DEFAULT ");
        sql.push_str(default.trim());
    }
    if !column.nullable {
        sql.push_str(" NOT NULL");
    }
    if let Some(collation) = &column.collation {
        write!(
            sql,
            " COLLATE {}",
            quote_identifier(engine, collation.trim())
        )
        .expect("writing to String cannot fail");
    }
    if engine == DatabaseEngine::Mysql {
        if let Some(comment) = &column.comment {
            write!(sql, " COMMENT {}", quote_literal(comment))
                .expect("writing to String cannot fail");
        }
    }
    Ok(sql)
}

pub(super) fn render_constraint(
    engine: DatabaseEngine,
    constraint: &Constraint,
) -> AppResult<String> {
    let name = quote_identifier(engine, &constraint.name);
    let columns = constraint
        .columns
        .iter()
        .map(|column| quote_identifier(engine, column))
        .collect::<Vec<_>>()
        .join(", ");
    let mut sql = match constraint.kind {
        ConstraintKind::Primary => format!("CONSTRAINT {name} PRIMARY KEY ({columns})"),
        ConstraintKind::Unique => format!("CONSTRAINT {name} UNIQUE ({columns})"),
        ConstraintKind::Foreign => {
            let reference =
                constraint
                    .referenced_relation
                    .as_ref()
                    .ok_or_else(|| AppError::Blocked {
                        reason: "foreign key is missing its referenced relation".into(),
                    })?;
            let referenced = constraint
                .referenced_columns
                .iter()
                .map(|column| quote_identifier(engine, column))
                .collect::<Vec<_>>()
                .join(", ");
            format!(
                "CONSTRAINT {name} FOREIGN KEY ({columns}) REFERENCES {} ({referenced})",
                quoted_ref(engine, reference)
            )
        }
        ConstraintKind::Check => format!(
            "CONSTRAINT {name} CHECK ({})",
            constraint
                .check_expression
                .as_deref()
                .ok_or_else(|| AppError::Blocked {
                    reason: "check constraint is missing its expression".into(),
                })?
        ),
    };
    if let Some(action) = &constraint.update_action {
        write!(sql, " ON UPDATE {}", action.trim()).expect("writing to String cannot fail");
    }
    if let Some(action) = &constraint.delete_action {
        write!(sql, " ON DELETE {}", action.trim()).expect("writing to String cannot fail");
    }
    if constraint.deferrable {
        if engine == DatabaseEngine::Mysql {
            return blocked("MySQL does not support deferrable constraints");
        }
        sql.push_str(" DEFERRABLE");
    }
    if !constraint.validated {
        if engine == DatabaseEngine::Postgres {
            sql.push_str(" NOT VALID");
        } else {
            return blocked("unvalidated constraints are unsupported by this database");
        }
    }
    Ok(sql)
}

pub(super) fn create_table(
    engine: DatabaseEngine,
    table: &TableDefinition,
) -> AppResult<Vec<String>> {
    let mut definitions = table
        .columns
        .iter()
        .map(|column| render_column(engine, column))
        .collect::<AppResult<Vec<_>>>()?;
    definitions.extend(
        table
            .constraints
            .iter()
            .map(|constraint| render_constraint(engine, constraint))
            .collect::<AppResult<Vec<_>>>()?,
    );
    let mut statements = vec![format!(
        "CREATE TABLE {} (\n    {}\n);",
        quoted_ref(engine, &table.relation),
        definitions.join(",\n    ")
    )];
    statements.extend(
        table
            .indexes
            .iter()
            .map(|index| create_index(engine, &table.relation, index))
            .collect::<AppResult<Vec<_>>>()?,
    );
    if let Some(comment) = &table.comment {
        match engine {
            DatabaseEngine::Postgres => statements.push(format!(
                "COMMENT ON TABLE {} IS {};",
                quoted_ref(engine, &table.relation),
                quote_literal(comment)
            )),
            DatabaseEngine::Mysql => statements.push(format!(
                "ALTER TABLE {} COMMENT = {};",
                quoted_ref(engine, &table.relation),
                quote_literal(comment)
            )),
            DatabaseEngine::Sqlite => {}
            DatabaseEngine::Mongodb => return blocked("MongoDB has no relational tables"),
        }
    }
    Ok(statements)
}

pub(super) fn create_index(
    engine: DatabaseEngine,
    relation: &ObjectRef,
    index: &Index,
) -> AppResult<String> {
    let keys = index
        .keys
        .iter()
        .map(|key| render_index_key(engine, key))
        .collect::<AppResult<Vec<_>>>()?
        .join(", ");
    let method = match (&index.method, engine) {
        (Some(method), DatabaseEngine::Postgres) => format!(" USING {}", method.trim()),
        (Some(method), DatabaseEngine::Mysql) => format!(" USING {}", method.trim()),
        (Some(_), DatabaseEngine::Sqlite) => {
            return blocked("SQLite does not support selecting an index method");
        }
        (Some(_), DatabaseEngine::Mongodb) => return blocked("MongoDB uses typed index APIs"),
        (None, _) => String::new(),
    };
    let include = if index.included_columns.is_empty() {
        String::new()
    } else if engine == DatabaseEngine::Postgres {
        format!(
            " INCLUDE ({})",
            index
                .included_columns
                .iter()
                .map(|column| quote_identifier(engine, column))
                .collect::<Vec<_>>()
                .join(", ")
        )
    } else {
        return blocked("included index columns are unsupported by this database");
    };
    let predicate = match &index.predicate {
        Some(predicate) if engine != DatabaseEngine::Mysql => {
            format!(" WHERE {}", predicate.trim())
        }
        Some(_) => return blocked("MySQL does not support partial index predicates"),
        None => String::new(),
    };
    Ok(format!(
        "CREATE {}INDEX {} ON {}{} ({keys}){include}{predicate};",
        if index.unique { "UNIQUE " } else { "" },
        quote_identifier(engine, &index.name),
        quoted_ref(engine, relation),
        method,
    ))
}

fn render_index_key(engine: DatabaseEngine, key: &IndexKey) -> AppResult<String> {
    let mut sql = match (&key.column, &key.expression) {
        (Some(column), None) => quote_identifier(engine, column),
        (None, Some(expression)) => {
            if engine == DatabaseEngine::Mysql {
                format!("({})", expression.trim())
            } else {
                expression.trim().to_string()
            }
        }
        _ => {
            return blocked("index keys must contain exactly one column or expression");
        }
    };
    if let Some(direction) = key.direction {
        sql.push_str(match direction {
            SortDirection::Asc => " ASC",
            SortDirection::Desc => " DESC",
        });
    }
    Ok(sql)
}

fn blocked<T>(reason: &str) -> AppResult<T> {
    Err(AppError::Blocked {
        reason: reason.into(),
    })
}
